name: main
on: 
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_SUPABASE_ENDPOINT: ${{ secrets.NEXT_PUBLIC_SUPABASE_ENDPOINT }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      NEXT_PUBLIC_SUPABASE_IMG_BUCKET: ${{secrets.NEXT_PUBLIC_SUPABASE_IMG_BUCKET}}
      OPENAI_API_KEY: ${{vars.OPENAI_API_KEY}}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build
        
      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./out